### PR TITLE
latest

### PR DESCRIPTION
**Pull request by coolzoom**

### CODE REVIEW

**Comment by coolzoom** [comment]
test merge

**Comment by coolzoom** [comment]
test merge

**Comment by coolzoom** [comment]
sorry this is a mistake

**Comment by Rochet2** [comment]
Would be cool to have a PR to fix the build with cmangos though :)

**Comment by coolzoom** [comment]
> Would be cool to have a PR to fix the build with cmangos though :)

yes i was trying to do so but did a wrong pull. i forked a latest cmangos tbc, the file structure changed a lot, still working on it and would take a while.

**Pull request closed without merging**
